{
    "ingredients": [
        {"name": "Abecean Longfin", "introduced": "Skyrim"},
        {"name": "Ancestor Moth Wing", "introduced": "Dawnguard"},
        {"name": "Ash Creep Cluster", "introduced": "Dragonborn"},
        {"name": "Ashen Grass Pod", "introduced": "Dragonborn"},
        {"name": "Ash Hopper Jelly", "introduced": "Dragonborn"},
        {"name": "Bear Claws", "introduced": "Skyrim"},
        {"name": "Bee", "introduced": "Skyrim"},
        {"name": "Beehive Husk", "introduced": "Skyrim"},
        {"name": "Bleeding Crown", "introduced": "Skyrim"},
        {"name": "Blisterwort", "introduced": "Skyrim"},
        {"name": "Blue Butterfly Wing", "introduced": "Skyrim"},
        {"name": "Blue Dartwing", "introduced": "Skyrim"},
        {"name": "Blue Mountain Flower", "introduced": "Skyrim"},
        {"name": "Boar Tusk", "introduced": "Dragonborn"},
        {"name": "Bone Meal", "introduced": "Skyrim"},
        {"name": "Briar Heart", "introduced": "Skyrim"},
        {"name": "Burnt Spriggan Wood", "introduced": "Dragonborn"},
        {"name": "Butterfly Wing", "introduced": "Skyrim"},
        {"name": "Canis Root", "introduced": "Skyrim"},
        {"name": "Charred Skeever Hide", "introduced": "Skyrim"},
        {"name": "Chaurus Eggs", "introduced": "Skyrim"},
        {"name": "Chaurus Hunter Antennae", "introduced": "Dawnguard"},
        {"name": "Chicken's Egg", "introduced": "Skyrim"},
        {"name": "Creep Cluster", "introduced": "Skyrim"},
        {"name": "Crimson Nirnroot", "introduced": "Skyrim"},
        {"name": "Cyrodilic Spadetail", "introduced": "Skyrim"},
        {"name": "Daedra Heart", "introduced": "Skyrim"},
        {"name": "Deathbell", "introduced": "Skyrim"},
        {"name": "Dragon's Tongue", "introduced": "Skyrim"},
        {"name": "Dwarven Oil", "introduced": "Skyrim"},
        {"name": "Ectoplasm", "introduced": "Skyrim"},
        {"name": "Elves Ear", "introduced": "Skyrim"},
        {"name": "Emperor Parasol Moss", "introduced": "Skyrim"},
        {"name": "Eye of Sabre Cat", "introduced": "Skyrim"},
        {"name": "Falmer Ear", "introduced": "Skyrim"},
        {"name": "Felsaad Tern Feathers", "introduced": "Dragonborn"},
        {"name": "Fire Salts", "introduced": "Skyrim"},
        {"name": "Fly Amanita", "introduced": "Skyrim"},
        {"name": "Frost Mirriam", "introduced": "Skyrim"},
        {"name": "Frost Salts", "introduced": "Skyrim"},
        {"name": "Garlic", "introduced": "Skyrim"},
        {"name": "Giant Lichen", "introduced": "Skyrim"},
        {"name": "Giant's Toe", "introduced": "Skyrim"},
        {"name": "Gleamblossom", "introduced": "Dawnguard"},
        {"name": "Glow Dust", "introduced": "Skyrim"},
        {"name": "Glowing Mushroom", "introduced": "Skyrim"},
        {"name": "Grass Pod", "introduced": "Skyrim"},
        {"name": "Hagraven Claw", "introduced": "Skyrim"},
        {"name": "Hagraven Feathers", "introduced": "Skyrim"},
        {"name": "Hanging Moss", "introduced": "Skyrim"},
        {"name": "Hawk Beak", "introduced": "Skyrim"},
        {"name": "Hawk Feathers", "introduced": "Skyrim"},
        {"name": "Hawk's Egg", "introduced": "Hearthfire"},
        {"name": "Histcarp", "introduced": "Skyrim"},
        {"name": "Honeycomb", "introduced": "Skyrim"},
        {"name": "Human Flesh", "introduced": "Skyrim"},
        {"name": "Human Heart", "introduced": "Skyrim"},
        {"name": "Ice Wraith Teeth", "introduced": "Skyrim"},
        {"name": "Imp Stool", "introduced": "Skyrim"},
        {"name": "Jazbay Grapes", "introduced": "Skyrim"},
        {"name": "Juniper Berries", "introduced": "Skyrim"},
        {"name": "Large Antlers", "introduced": "Skyrim"},
        {"name": "Lavendar", "introduced": "Skyrim"},
        {"name": "Luna Moth Wing", "introduced": "Skyrim"},
        {"name": "Moon Sugar", "introduced": "Skyrim"},
        {"name": "Mora Tapinella", "introduced": "Skyrim"},
        {"name": "Mudcrab Chitin", "introduced": "Skyrim"},
        {"name": "Namira's Rot", "introduced": "Skyrim"},
        {"name": "Netch Jelly", "introduced": "Dragonborn"},
        {"name": "Nightshade", "introduced": "Skyrim"},
        {"name": "Nirnoot", "introduced": "Skyrim"},
        {"name": "Nordic Barnacle", "introduced": "Skyrim"},
        {"name": "Orange Dartwing", "introduced": "Skyrim"},
        {"name": "Pearl", "introduced": "Skyrim"},
        {"name": "Pine Thrush Egg", "introduced": "Skyrim"},
        {"name": "Poison Bloom", "introduced": "Dawnguard"},
        {"name": "Powdered Mammoth Tusk", "introduced": "Skyrim"},
        {"name": "Purple Mountain Flower", "introduced": "Skyrim"},
        {"name": "Red Mountain Flower", "introduced": "Skyrim"},
        {"name": "River Betty", "introduced": "Skyrim"},
        {"name": "Rock Warbler Egg", "introduced": "Skyrim"},
        {"name": "Sabre Cat Tooth", "introduced": "Skyrim"},
        {"name": "Salmon Roe", "introduced": "Hearthfire"},
        {"name": "Salt Pile", "introduced": "Skyrim"},
        {"name": "Scaly Pholiota", "introduced": "Skyrim"},
        {"name": "Scathecraw", "introduced": "Dragonborn"},
        {"name": "Silverside Perch", "introduced": "Skyrim"},
        {"name": "Skeever Tail", "introduced": "Skyrim"},
        {"name": "Slaughterfish Egg", "introduced": "Skyrim"},
        {"name": "Slaughterfish Scales", "introduced": "Skyrim"},
        {"name": "Small Antlers", "introduced": "Skyrim"},
        {"name": "Small Pearl", "introduced": "Skyrim"},
        {"name": "Snowberries", "introduced": "Skyrim"},
        {"name": "Spawn Ash", "introduced": "Dragonborn"},
        {"name": "Spider Egg", "introduced": "Skyrim"},
        {"name": "Spriggan Sap", "introduced": "Skyrim"},
        {"name": "Swamp Fungal Pod", "introduced": "Skyrim"},
        {"name": "Taproot", "introduced": "Skyrim"},
        {"name": "Thistle Branch", "introduced": "Skyrim"},
        {"name": "Torchbug Thorax", "introduced": "Skyrim"},
        {"name": "Trama Root", "introduced": "Dragonborn"},
        {"name": "Troll Fat", "introduced": "Skyrim"},
        {"name": "Tundra Cotton", "introduced": "Skyrim"},
        {"name": "Vampire Dust", "introduced": "Skyrim"},
        {"name": "Void Salts", "introduced": "Skyrim"},
        {"name": "Wheat", "introduced": "Skyrim"},
        {"name": "White Cap", "introduced": "Skyrim"},
        {"name": "Wisp Wrappings", "introduced": "Skyrim"},
        {"name": "Yellow Mountain Flower", "introduced": "Dawnguard"}
    ],
    "effects": [
        "Cure Disease",
        "Damage Health",
        "Damage Magicka",
        "Damage Magicka Regen",
        "Damage Stamina",
        "Damage Stamina Regen",
        "Fear",
        "Fortify Alteration",
        "Fortify Barter",
        "Fortify Block",
        "Fortify Carry Weight",
        "Fortify Conjuration",
        "Fortify Destruction",
        "Fortify Enchanting",
        "Fortify Health",
        "Fortify Heavy Armor",
        "Fortify Illusion",
        "Fortify Light Armor",
        "Fortify Lockpicking",
        "Fortify Magicka",
        "Fortify Marksman",
        "Fortify One-handed",
        "Fortify Restoration",
        "Fortify Smithing",
        "Fortify Sneak",
        "Fortify Stamina",
        "Fortify Two-handed",
        "Frenzy",
        "Invisibility",
        "Lingering Damage Health",
        "Lingering Damage Magicka",
        "Lingering Damage Stamina",
        "Paralysis",
        "Ravage Health",
        "Ravage Magicka",
        "Ravage Stamina",
        "Regenerate Health",
        "Regenerate Magicka",
        "Regenerate Stamina",
        "Resist Fire",
        "Resist Frost",
        "Resist Magic",
        "Resist Poison",
        "Resist Shock",
        "Restore Health",
        "Restore Magicka",
        "Restore Stamina",
        "Slow",
        "Waterbreathing",
        "Weakness to Fire",
        "Weakness to Frost",
        "Weakness to Magic",
        "Weakness to Poison",
        "Weakness to Shock"
    ]
}